"""task definitions r2

Revision ID: 0818749b8790
Revises: 378d219791f8
Create Date: 2021-04-16 10:42:10.495298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0818749b8790'
down_revision = '378d219791f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('taskorder', sa.Integer(), nullable=False),
    sa.Column('taskconfig', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.dataset_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.add_column('annotations', sa.Column('task_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotations', 'task_id')
    op.drop_table('tasks')
    # ### end Alembic commands ###
