"""initial migration

Revision ID: 325f71cba319
Revises: 
Create Date: 2020-07-08 20:39:18.980285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '325f71cba319'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('displayname', sa.String(), nullable=True),
    sa.Column('pwhash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('datasets',
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('dsmetadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('dataset_id')
    )
    op.create_table('annotations',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('sample', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.dataset_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('owner_id', 'dataset_id', 'sample')
    )
    op.create_table('datasetcontent',
    sa.Column('sample_index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('sample', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.dataset_id'], ),
    sa.PrimaryKeyConstraint('sample_index', 'dataset_id', 'sample')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datasetcontent')
    op.drop_table('annotations')
    op.drop_table('datasets')
    op.drop_table('users')
    # ### end Alembic commands ###
