"""initial migration

Revision ID: 4c891728d76d
Revises: 
Create Date: 2020-07-03 09:39:19.898617

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c891728d76d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('annotations')
    op.drop_table('datasets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('dataset_id', sa.INTEGER(), server_default=sa.text("nextval('datasets_dataset_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dsmetadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.uid'], name='datasets_owner_id_fkey'),
    sa.PrimaryKeyConstraint('dataset_id', name='datasets_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('annotations',
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sample', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.dataset_id'], name='annotations_dataset_id_fkey'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.uid'], name='annotations_owner_id_fkey'),
    sa.PrimaryKeyConstraint('owner_id', 'dataset_id', 'sample', name='annotations_pkey')
    )
    op.create_table('users',
    sa.Column('uid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pwhash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('displayname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uid', name='users_pkey')
    )
    # ### end Alembic commands ###
