"""task definitions

Revision ID: 840067add8f5
Revises: 378d219791f8
Create Date: 2021-04-16 09:29:47.029215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840067add8f5'
down_revision = '378d219791f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('taskorder', sa.Integer(), nullable=False),
    sa.Column('taskconfig', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.dataset_id'], ),
    sa.PrimaryKeyConstraint('task_id', 'dataset_id')
    )
    op.add_column('annotations', sa.Column('task_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotations', 'task_id')
    op.drop_table('tasks')
    # ### end Alembic commands ###
