version: '3'
services:
    web-prod:
        build:
            context: .
            dockerfile: "Dockerfile.prod"
        ports:
            - "5000:5000"
        volumes:
            - ${PWD}/app:/home/omenuser/app/app
            - ${PWD}/logs:/home/omenuser/logs
            - ${PWD}/config.json:/home/omenuser/app/config.json
        environment:
            - LOGLEVEL=debug
            - WORKERS_PER_CORE=1
    db:
        image: postgres:12.3
        restart: always
        volumes:
            - ${PWD}/dbdata:/var/lib/postgresql/data
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_USER=omenusr
            - POSTGRES_PASSWORD=omenusr
